from django.shortcuts import render
import json


def fn(request):
    # with open("nltk/main_habr_04_04.json", "r") as file:
    #     f = json.load(file)
    # context = {'title': f[0]["title"], 'data': f[0]["description"]}
    # context = {'data': '<div class="sources_rel"><p><strong>Источники:</strong></p><ul class="related"><li><a href="http://www.microsoft.com" target="_blank" title="microsoft.com">microsoft.com</a></li><li><a href="http://www.neowin.net/" target="_blank" title="Neowin">Neowin</a></li></ul></div>'}
    context = {'data': '"<div class=\"text-in-block\"><p>Чтобы помочь соискателям, исследовательская компания WalletHub ежегодно собирает данные и составляет рейтинг лучших и худших мест для специалистов STEM.</p><p><br/></p><p>Для исследования сравнивали 100 самых больших городских района США по численности населения. Их оценивали по трем критериям:</p><ul><li dir=\"ltr\">качество жизни – стоимость жилья, развитость инфраструктуры, места для отдыха и пр.;</li><li dir=\"ltr\">профессиональные возможности – количество вакансий в сфере STEM, заработная плата, карьерный рост и пр.;</li><li dir=\"ltr\">дружественность в отношении STEM – расходы на возможность получения новых знаний, уровень образовательной программы и пр.</li></ul><p><br/></p><p>Критерии оценивались по 19 показателям, каждый из которых имел свой вес. Так, максимальная оценка составила 100 баллов и отражала наиболее благоприятные условия для работы.</p><p><br/></p><p>Интересно, что некоторые города получили высокую оценку по критерию “профессиональные возможности”, но по качеству жизни заработали минимум, т.к. в них очень высокий ценник на жилье. Например, Сиэтл, который стал лучшим в ТОПе, и Сан-Франциско, занявший 9-ую позицию. </p><p><br/></p><p>Также были города, где условия для жизни оценены высоко, но перспективы для развития в сфере IT – оставляют желать лучшего. Таким городом стал Дейтон. Он получил первое место по критерию “качество жизни”, но в общей таблице остался на 11 позиции.</p><p><br/></p><p>В 10-ке лидеров оказались два стремительно развивающихся IT-хаба – Атланта и Остин. </p><p>Список ТОП-10 городов согласно исследованиям <noindex><a href=\"https://wallethub.com/edu/best-worst-metro-areas-for-stem-professionals/9200\" rel=\"nofollow\" target=\"_blank\">WalletHub</a></noindex>:</p><p><br/></p><p style=\"text-align: center;\"><img class=\"fr-fic fr-dib\" src=\"/img/news/1644239428.png\"/></p><p><br/></p><p>Весь список из 100 наиболее привлекательных городов США для специалистов STEM – <noindex><a href=\"https://wallethub.com/edu/best-worst-metro-areas-for-stem-professionals/9200\" rel=\"nofollow\" target=\"_blank\">здесь</a></noindex>.</p></div>"'}
    return render(request, "nltk/nltk.html", context)
